# Generated by Django 4.1.7 on 2023-04-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
