# Generated by Django 4.1.7 on 2023-04-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_doctor_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('', ''), ('Consult', 'Consult'), ('Radiology', 'Radiology')], default='Consult', max_length=50),
        ),
    ]
