# Generated by Django 4.1.7 on 2023-04-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('Radiology', 'Radiology'), ('Consult', 'Consult'), ('', '')], max_length=50),
        ),
    ]
