# Generated by Django 4.1.7 on 2023-04-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Allergies', 'Allergies'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('Genomics', 'Genomics'), ('Hematology', 'Hematology'), ('Immunology', 'Immunology'), ('Infectious Diseases', 'Infectious Diseases'), ('Neurology', 'Neurology'), ('Gynecology', 'Gynecology'), ('Oncology', 'Oncology'), ('Psychiatry', 'Psychiatry'), ('Radiology', 'Radiology'), ('Routine Check-Up', 'Routine Check-Up'), ('Urology', 'Urology'), ('Vaccines', 'Vaccines')], max_length=20),
        ),
    ]
